import pandas as pd
from pathlib import Path

INPUT_PATH = Path("data/processed/hotel_catalog_clean.csv")
REPORT_PATH = Path("data/processed/hotel_data_validation_report.txt")
SAMPLE_PATH = Path("data/processed/manual_verification_sample.csv")


def check_score_range(series, min_value=0, max_value=10):
    numeric = pd.to_numeric(series, errors="coerce")
    invalid = numeric.dropna()[
        (numeric.dropna() < min_value) | (numeric.dropna() > max_value)
    ]
    return len(invalid)


def main():
    df = pd.read_csv(INPUT_PATH)

    total_rows = len(df)

    missing_hotel_name = (
        df["hotel_name"].isna().sum()
        + (df["hotel_name"].astype(str).str.strip() == "").sum()
    )
    missing_source = (
        df["source"].isna().sum() + (df["source"].astype(str).str.strip() == "").sum()
    )

    duplicate_rows = df.duplicated(
        subset=[
            "hotel_name",
            "location",
            "room_type",
            "bed_type",
            "room_comment",
            "source",
        ]
    ).sum()

    invalid_hotel_rating = (
        check_score_range(df["hotel_rating"]) if "hotel_rating" in df.columns else 0
    )
    invalid_review_score = (
        check_score_range(df["review_score"]) if "review_score" in df.columns else 0
    )
    invalid_room_score = (
        check_score_range(df["room_score"]) if "room_score" in df.columns else 0
    )

    missing_location = (
        df["location"].isna().sum()
        + (df["location"].astype(str).str.strip() == "").sum()
    )
    missing_room_type = (
        df["room_type"].isna().sum()
        + (df["room_type"].astype(str).str.strip() == "").sum()
    )
    missing_bed_type = (
        df["bed_type"].isna().sum()
        + (df["bed_type"].astype(str).str.strip() == "").sum()
    )
    missing_room_comment = (
        df["room_comment"].isna().sum()
        + (df["room_comment"].astype(str).str.strip() == "").sum()
    )

    source_counts = df["source"].value_counts()

    report = f"""
TravelMind RAG - Hotel Data Validation Report

Total rows: {total_rows}

Source distribution:
{source_counts.to_string()}

Basic checks:
- Missing hotel name: {missing_hotel_name}
- Missing source: {missing_source}
- Duplicate rows: {duplicate_rows}

Missing field counts:
- Missing location: {missing_location}
- Missing room type: {missing_room_type}
- Missing bed type: {missing_bed_type}
- Missing room comment: {missing_room_comment}

Score range checks:
- Invalid hotel_rating values outside 0-10: {invalid_hotel_rating}
- Invalid review_score values outside 0-10: {invalid_review_score}
- Invalid room_score values outside 0-10: {invalid_room_score}

Price policy:
- Room price is excluded from RAG chunks and final answer generation.
- Reason: hotel prices can vary by country, currency, season, date and room conditions.
- The assistant will not make hotel recommendations based on price.

Data reliability note:
- The project uses public Kaggle hotel datasets.
- The data is not generated by us and is not fully synthetic.
- The system will not claim that every hotel field is currently up to date.
- The assistant will answer only based on available dataset fields and will clearly state when information is insufficient.
"""

    REPORT_PATH.write_text(report, encoding="utf-8")

    sample_columns = [
        "hotel_id",
        "hotel_name",
        "location",
        "hotel_rating",
        "review_score",
        "room_score",
        "review_count",
        "room_type",
        "bed_type",
        "room_comment",
        "source",
    ]

    existing_columns = [col for col in sample_columns if col in df.columns]

    sample = df[existing_columns].sample(n=min(30, len(df)), random_state=42)

    sample.to_csv(SAMPLE_PATH, index=False, encoding="utf-8")

    print("Validation report oluşturuldu:", REPORT_PATH)
    print("Manual verification sample oluşturuldu:", SAMPLE_PATH)

    print(report)


if __name__ == "__main__":
    main()
